### ISSUE TITLE
No module named 'datasets' 'utils'

### ISSUE THREAD

**Issue by heerduo** [huawei-noah/GAN-pruning#1]
Is the code incomplete?

**Comment by TheLostIn** [comment]
I think the code was incomplete.
You can copy the code files :`datasets.py` and `utils.py` from [Pytorch-CycleGAN](https://github.com/aitorzip/PyTorch-CycleGAN).

**Comment by shuh15** [comment]
datasets.py and utils.py have been added.

**Comment by TheLostIn** [comment]
Thank you for the adding.
I had also found some other bugs.
1.And there's also no `cfg_full_mask` in function `caculate_fitness_for_first_time`.
2.`start_mask=torch.ones(3)` may cause error,because the follwing code are using `np.`
```
cfg_mask_start=np.ones(start_mask.shape)-start_mask
idx0 = np.squeeze(np.argwhere(np.asarray(cfg_mask_start)))
idx1 = np.squeeze(np.argwhere(np.asarray(cfg_mask_end)))
```

**Comment by shuh15** [comment]
> Thank you for the adding.
> I had also found some other bugs.
> 1.And there's also no `cfg_full_mask` in function `caculate_fitness_for_first_time`.
> 2.`start_mask=torch.ones(3)` may cause error,because the follwing code are using `np.`
> 
> ```
> cfg_mask_start=np.ones(start_mask.shape)-start_mask
> idx0 = np.squeeze(np.argwhere(np.asarray(cfg_mask_start)))
> idx1 = np.squeeze(np.argwhere(np.asarray(cfg_mask_end)))
> ```

Thanks for your comment, code has been updated.
