### ISSUE TITLE
Hardware setting and GPU hours of ManiDP

### ISSUE THREAD

**Issue by sseung0703** [huawei-noah/GAN-pruning#16]
Hi, I'm CNN light-weighting researcher, and I'm building a filter pruning leaderboard for better comparison.
I think GPU hour for search and training is important to evaluate the pruning algorithms, but you didn't report it.
Would you let me know GPU hours for each ImageNet configuration?

**Comment by yehuitang** [comment]
Thanks for your leaderboard. This method requires similar time with training a model regularly.
