### ISSUE TITLE
No acceleration for ManiDP

### ISSUE THREAD

**Issue by NoLookDefense** [huawei-noah/GAN-pruning#22]
Hello. Thanks for your work. I have some confusions about how the Manidp achieve acceleration.
I found that the convolution is forwarded without masks. 
https://github.com/yehuitang/Pruning/blob/5c8bc0d780fab41e1bd894b0360bd50e14cd0571/ManiDP/models/resnet_imagenet.py#L117
The mask only make sense after the convolution which simply multiplying the results. 
https://github.com/yehuitang/Pruning/blob/5c8bc0d780fab41e1bd894b0360bd50e14cd0571/ManiDP/models/resnet_imagenet.py#L123
In this situation, the FLOPs will always be the addition of original model and gate module, which is slower than a single original model. 
So, how the FLOPs reduction is calculated? Can you provide the codes for FLOPs evaluation?

**Comment by yehuitang** [comment]
Hi. This is a Demo using 0,1 mask. You can calculate FLOPs for each input instance and obtain the average value over the whole dataset.
