### ISSUE TITLE
No module named moxing and where i can get it?

### ISSUE THREAD

**Issue by chenxiang204** [huawei-noah/GAN-pruning#3]

**Comment by TheLostIn** [comment]
The module named moxing only works in huawei claud.
You can prepare those files by yourself.

**Comment by shuh15** [comment]
The moxing api is used only for moving data in huawei cloud service, if you don't use huawei cloud, you can ignore the api and related code.

**Comment by chenxiang204** [comment]
Thank you!

**Comment by pyl62112991** [comment]
how can  I prepare those files by myself if i nit work in huawei claud?

**Comment by shuh15** [comment]
> how can I prepare those files by myself if i nit work in huawei claud?

Just specify the filepath where you save the data and files in the script.
