### ISSUE TITLE
train errors

### ISSUE THREAD

**Issue by pyl62112991** [huawei-noah/GAN-pruning#5]
![2019-10-23 19-41-37屏幕截图](https://user-images.githubusercontent.com/47971541/67389509-584c3180-f5cd-11e9-9ff3-b0ac3cf1ed14.png)

when i run the search.py code appear the problem as in the picture,what should i set in the problem?

**Comment by ElephantGit** [comment]
Could you share how to get the pth  files and datasets? thx~~

**Comment by shuh15** [comment]
you could refer this link https://github.com/aitorzip/PyTorch-CycleGAN
