### ISSUE TITLE
运行代码缺少MoXing支持和cache/等文件夹及相关的.pth文件等

### ISSUE THREAD

**Issue by Louxiaoxiao** [huawei-noah/GAN-pruning#8]
请问一下，在运行过程中发现没有MoXing支持并且缺少部分cache/和相关的.pth文件，并且目前没有使用HUAWEI 云服务器的条件 请问贵团队有没有其他可以运行代码的方法？多谢！O(∩_∩)O

**Comment by Louxiaoxiao** [comment]
During running the code, I found that there is no MoXing, some cache/ and related .pth files are missing, and there is no condition for using Huawei cloud server. Do you have any other way to run the code? Thank you very much!

**Comment by shuh15** [comment]
Hi, please remove Moxing related code if you couldn't use huawei cloud server. The pretrained full model could be trained on your specific need, please refer this link.  https://github.com/aitorzip/PyTorch-CycleGAN
